INSERT INTO AUTHOR(ID,NAME, ADDRESS) VALUES ('1', 'JOHN', 'DA NANG');


INSERT INTO CUSTOM_GROUP(ID, GROUP_NAME) VALUES('1', 'ADMIN');
INSERT INTO CUSTOM_GROUP(ID, GROUP_NAME) VALUES('2', 'CLIENT');
INSERT INTO CUSTOM_GROUP(ID, GROUP_NAME) VALUES('3', 'PILOT');